// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"


import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SwipeInsposController from "./swipe_inspos_controller"
application.register("swipe-inspos", SwipeInsposController)

import EditEventController from "./edit_event_controller"
application.register("edit-event", EditEventController)

import KeywordsController from "./keywords_controller"
application.register("keywords", KeywordsController)
